### ISSUE TITLE
KituraBluePic-server make fails

### ISSUE THREAD

**Issue by lsteck** [IBM-Swift/Kitura-BluePic#4]
Using DEVELOPMENT-SNAPSHOT-2016-05-03-a

On the **master** Branch I receive several Build errors on several of the packages

On the **develop** Branch I receive the following error:
Compile CHttpParser utils.c
Compile CHttpParser http_parser.c
Compile Swift Module 'LoggerAPI' (1 sources)
Compile Swift Module 'Socket' (3 sources)
Compile Swift Module 'SwiftyJSON' (3 sources)
Compile Swift Module 'KituraTemplateEngine' (1 sources)
Compile Swift Module 'KituraSys' (4 sources)
Compile Swift Module 'HeliumLogger' (1 sources)
Compile Swift Module 'KituraNet' (12 sources)
Compile Swift Module 'SwiftRedis' (4 sources)
Compile Swift Module 'Kitura' (20 sources)
Compile Swift Module 'CouchDB' (5 sources)
Compile Swift Module 'CouchDBSample' (1 sources)
Linking .build/debug/CouchDBSample
ld: library not found for -lCHttpParser for architecture x86_64
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: build had 1 command failures
error: exit(1): /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-05-03-a.xctoolchain/usr/bin/swift-build-tool -f /Users/lsteck/git/kitura/Kitura-BluePic/KituraBluePic-server/.build/debug.yaml
make: *** [build] Error 1

**Comment by kweinmeister** [comment]
I tried to reproduce using 5/3 and develop branch and it compiled running `swift build`:
 
...
Compile Swift Module 'KituraTemplateEngine' (1 sources)
Compile Swift Module 'HeliumLogger' (1 sources)
Compile Swift Module 'KituraSys' (4 sources)
Linking CHttpParser
Compile Swift Module 'KituraNet' (12 sources)
Compile Swift Module 'SwiftRedis' (4 sources)
Compile Swift Module 'Kitura' (20 sources)
Compile Swift Module 'CouchDB' (5 sources)
Compile Swift Module 'CouchDBSample' (1 sources)
Linking .build/debug/CouchDBSample
Compile Swift Module 'KituraSession' (7 sources)
Compile Swift Module 'Credentials' (6 sources)
Compile Swift Module 'CredentialsFacebookToken' (1 sources)
Compile Swift Module 'CredentialsGoogleToken' (1 sources)
Compile Swift Module 'KituraBluePicserver' (4 sources)
Linking .build/debug/KituraBluePic-server

**Comment by lsteck** [comment]
On develop branch running swift build I see
swift build
note: you may be able to install libcurl using your system-packager:

    brew install curl
.....
and the same link error 
Linking .build/debug/CouchDBSample
ld: library not found for -lCHttpParser for architecture x86_64
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: build had 1 command failures
error: exit(1): /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-05-03-a.xctoolchain/usr/bin/swift-build-tool -f /Users/lsteck/git/kitura/Kitura-BluePic/KituraBluePic-server/.build/debug.yaml

When installing curl  I see:
brew install curl
==> Downloading https://homebrew.bintray.com/bottles/curl-7.48.0.el_capitan.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring curl-7.48.0.el_capitan.bottle.1.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/curl/lib
    CPPFLAGS: -I/usr/local/opt/curl/include


zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/curl/7.48.0: 362 files, 2.5M

and when I run swift build I get same note to install libcurl and same link error

**Comment by lsteck** [comment]
After removing the Projects and .build folders with
rm -rf Packages 
rm -rf .build 

The swift build command works on the develop branch
